spring:
  application:
    name: autenticacaoautorizacaojwt
  server: 8080
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    hikari:
      pool-name: H2 Pool
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
