server:
  port: 8080

spring:
  application:
    name: autenticacaoautorizacaojwt
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

keys:
  jwt:
    secret: e3c36c42-5111-4d47-b4b9-96d9bdee5037


